CREATe TABLE "user"("id" SERIAL8  PRIMARY KEY UNIQUE,"username" VARCHAR NOT NULL,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"bio" VARCHAR NULL,"image" VARCHAR NULL);
ALTER TABLE "user" ADD CONSTRAINT "unique_username" UNIQUE("username");
ALTER TABLE "user" ADD CONSTRAINT "unique_email" UNIQUE("email");
CREATe TABLE "article"("id" SERIAL8  PRIMARY KEY UNIQUE,"slug" VARCHAR NOT NULL,"title" VARCHAR NOT NULL,"description" VARCHAR NOT NULL,"body" VARCHAR NOT NULL,"author_id" INT8 NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL);
ALTER TABLE "article" ADD CONSTRAINT "unique_slug" UNIQUE("slug");
ALTER TABLE "article" ADD CONSTRAINT "article_author_id_fkey" FOREIGN KEY("author_id") REFERENCES "user"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "tag"("id" SERIAL8  PRIMARY KEY UNIQUE,"name" VARCHAR NOT NULL);
ALTER TABLE "tag" ADD CONSTRAINT "unique_tag_name" UNIQUE("name");
CREATe TABLE "article_tag"("id" SERIAL8  PRIMARY KEY UNIQUE,"article_id" INT8 NOT NULL,"tag_id" INT8 NOT NULL);
ALTER TABLE "article_tag" ADD CONSTRAINT "unique_article_tag" UNIQUE("article_id","tag_id");
ALTER TABLE "article_tag" ADD CONSTRAINT "article_tag_article_id_fkey" FOREIGN KEY("article_id") REFERENCES "article"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "article_tag" ADD CONSTRAINT "article_tag_tag_id_fkey" FOREIGN KEY("tag_id") REFERENCES "tag"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "comment"("id" SERIAL8  PRIMARY KEY UNIQUE,"body" VARCHAR NOT NULL,"author_id" INT8 NOT NULL,"article_id" INT8 NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL);
ALTER TABLE "comment" ADD CONSTRAINT "comment_author_id_fkey" FOREIGN KEY("author_id") REFERENCES "user"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "comment" ADD CONSTRAINT "comment_article_id_fkey" FOREIGN KEY("article_id") REFERENCES "article"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "follow"("id" SERIAL8  PRIMARY KEY UNIQUE,"follower_id" INT8 NOT NULL,"followed_id" INT8 NOT NULL);
ALTER TABLE "follow" ADD CONSTRAINT "unique_follow" UNIQUE("follower_id","followed_id");
ALTER TABLE "follow" ADD CONSTRAINT "follow_follower_id_fkey" FOREIGN KEY("follower_id") REFERENCES "user"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "follow" ADD CONSTRAINT "follow_followed_id_fkey" FOREIGN KEY("followed_id") REFERENCES "user"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "favorite"("id" SERIAL8  PRIMARY KEY UNIQUE,"user_id" INT8 NOT NULL,"article_id" INT8 NOT NULL);
ALTER TABLE "favorite" ADD CONSTRAINT "unique_favorite" UNIQUE("user_id","article_id");
ALTER TABLE "favorite" ADD CONSTRAINT "favorite_user_id_fkey" FOREIGN KEY("user_id") REFERENCES "user"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "favorite" ADD CONSTRAINT "favorite_article_id_fkey" FOREIGN KEY("article_id") REFERENCES "article"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
