ALTER TABLE "user" ADD COLUMN "role" VARCHAR NOT NULL DEFAULT 'RegularRole';
CREATe TABLE "visitor"("id" SERIAL8  PRIMARY KEY UNIQUE,"ip" VARCHAR NOT NULL,"user_agent" VARCHAR NOT NULL,"path" VARCHAR NOT NULL,"timestamp" TIMESTAMP WITH TIME ZONE NOT NULL);
CREATe TABLE "log"("id" SERIAL8  PRIMARY KEY UNIQUE,"level" VARCHAR NOT NULL,"message" VARCHAR NOT NULL,"source" VARCHAR NOT NULL,"timestamp" TIMESTAMP WITH TIME ZONE NOT NULL,"user_id" INT8 NULL);
ALTER TABLE "log" ADD CONSTRAINT "log_user_id_fkey" FOREIGN KEY("user_id") REFERENCES "user"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
