# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 nixos/nix:latest

# Enable flakes and disable sandboxing
RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf && \
    echo "sandbox = false" >> /etc/nix/nix.conf && \
    echo "filter-syscalls = false" >> /etc/nix/nix.conf && \
    echo "substituters = https://cache.nixos.org https://cache.iog.io https://rinn7e.cachix.org" >> /etc/nix/nix.conf && \
    echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= rinn7e.cachix.org-1:Nt+WWMAPnqJ6mrDtLvNOdJOsH+CZsygvwupCb99aXbM=" >> /etc/nix/nix.conf

WORKDIR /app

# Copy the source code
COPY --link . .

# Run a Nix dry-run using a persistent Docker cache for Nix's Git/eval databases
RUN --mount=type=cache,target=/root/.cache/nix \
    nix build path:.#default --dry-run \
    --extra-experimental-features "nix-command flakes" \
    --option sandbox false \
    --option filter-syscalls false
