components:
  schemas:
    Article:
      properties:
        author:
          $ref: '#/components/schemas/Profile'
        body:
          type: string
        createdAt:
          $ref: '#/components/schemas/UTCTime'
        description:
          type: string
        favorited:
          type: boolean
        favoritesCount:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
        slug:
          type: string
        tagList:
          items:
            type: string
          type: array
        title:
          type: string
        updatedAt:
          $ref: '#/components/schemas/UTCTime'
      required:
      - slug
      - title
      - description
      - body
      - tagList
      - createdAt
      - updatedAt
      - favorited
      - favoritesCount
      - author
      type: object
    ArticleListResponse:
      properties:
        articles:
          items:
            $ref: '#/components/schemas/Article'
          type: array
        articlesCount:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      required:
      - articles
      - articlesCount
      type: object
    ArticleResponse:
      properties:
        article:
          $ref: '#/components/schemas/Article'
      required:
      - article
      type: object
    Comment:
      properties:
        author:
          $ref: '#/components/schemas/Profile'
        body:
          type: string
        createdAt:
          $ref: '#/components/schemas/UTCTime'
        id:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
        updatedAt:
          $ref: '#/components/schemas/UTCTime'
      required:
      - id
      - createdAt
      - updatedAt
      - body
      - author
      type: object
    CommentListResponse:
      properties:
        comments:
          items:
            $ref: '#/components/schemas/Comment'
          type: array
      required:
      - comments
      type: object
    CommentResponse:
      properties:
        comment:
          $ref: '#/components/schemas/Comment'
      required:
      - comment
      type: object
    LoginUserRequest:
      properties:
        user:
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
          type: object
      required:
      - user
      type: object
    MetadataResponse:
      properties:
        appVersion:
          type: string
        lastCommitHash:
          type: string
        lastRanMigration:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      required:
      - appVersion
      - lastCommitHash
      type: object
    NewArticleRequest:
      properties:
        article:
          properties:
            body:
              type: string
            description:
              type: string
            tagList:
              items:
                type: string
              type: array
            title:
              type: string
          required:
          - title
          - description
          - body
          type: object
      required:
      - article
      type: object
    NewCommentRequest:
      properties:
        comment:
          properties:
            body:
              type: string
          required:
          - body
          type: object
      required:
      - comment
      type: object
    NewUserRequest:
      properties:
        user:
          properties:
            email:
              type: string
            password:
              type: string
            username:
              type: string
          required:
          - username
          - email
          - password
          type: object
      required:
      - user
      type: object
    Profile:
      properties:
        bio:
          type: string
        following:
          type: boolean
        image:
          type: string
        username:
          type: string
      required:
      - username
      - following
      type: object
    ProfileResponse:
      properties:
        profile:
          $ref: '#/components/schemas/Profile'
      required:
      - profile
      type: object
    TagListResponse:
      properties:
        tags:
          items:
            type: string
          type: array
      required:
      - tags
      type: object
    UTCTime:
      example: 2016-07-22T00:00:00Z
      format: yyyy-mm-ddThh:MM:ssZ
      type: string
    UpdateArticleRequest:
      properties:
        article:
          properties:
            body:
              type: string
            description:
              type: string
            tagList:
              items:
                type: string
              type: array
            title:
              type: string
          type: object
      required:
      - article
      type: object
    UpdateUserRequest:
      properties:
        user:
          properties:
            bio:
              type: string
            email:
              type: string
            image:
              type: string
            password:
              type: string
            username:
              type: string
          type: object
      required:
      - user
      type: object
    User:
      properties:
        bio:
          type: string
        email:
          type: string
        image:
          type: string
        token:
          type: string
        username:
          type: string
      required:
      - email
      - token
      - username
      type: object
    UserResponse:
      properties:
        user:
          $ref: '#/components/schemas/User'
      required:
      - user
      type: object
  securitySchemes:
    jwt:
      description: 'JWT Bearer token format: Token <JWT_TOKEN>'
      in: header
      name: Authorization
      type: apiKey
info:
  description: RealWorld Conduit API backend using Servant, Postgres, and Esqueleto!
  title: Conduit API
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/articles:
    get:
      description: Get a list of recent articles
      parameters:
      - in: query
        name: tag
        required: false
        schema:
          type: string
      - in: query
        name: author
        required: false
        schema:
          type: string
      - in: query
        name: favorited
        required: false
        schema:
          type: string
      - in: query
        name: limit
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      - in: query
        name: offset
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ArticleListResponse'
          description: ''
        '400':
          description: Invalid `offset` or `limit` or `favorited` or `author` or `tag`
      summary: Get Articles
      tags:
      - Articles
    post:
      description: Create a new article
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/NewArticleRequest'
      responses:
        '201':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
          description: ''
        '400':
          description: Invalid `body`
      summary: Create Article
      tags:
      - Articles
  /api/articles/feed:
    get:
      description: Get a feed of recent articles from followed users
      parameters:
      - in: query
        name: limit
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      - in: query
        name: offset
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ArticleListResponse'
          description: ''
        '400':
          description: Invalid `offset` or `limit`
      summary: Get Feed
      tags:
      - Articles
  /api/articles/{slug}:
    delete:
      description: Delete an article by slug
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8: {}
          description: ''
        '404':
          description: '`slug` not found'
      summary: Delete Article
      tags:
      - Articles
    get:
      description: Get a single article by slug
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
          description: ''
        '404':
          description: '`slug` not found'
      summary: Get Article
      tags:
      - Articles
    put:
      description: Update an article by slug
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/UpdateArticleRequest'
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
          description: ''
        '400':
          description: Invalid `body`
        '404':
          description: '`slug` not found'
      summary: Update Article
      tags:
      - Articles
  /api/articles/{slug}/comments:
    get:
      description: Get comments for an article
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/CommentListResponse'
          description: ''
        '404':
          description: '`slug` not found'
      summary: Get Comments
      tags:
      - Articles
    post:
      description: Create a comment for an article
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/NewCommentRequest'
      responses:
        '201':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/CommentResponse'
          description: ''
        '400':
          description: Invalid `body`
        '404':
          description: '`slug` not found'
      summary: Create Comment
      tags:
      - Articles
  /api/articles/{slug}/comments/{id}:
    delete:
      description: Delete a comment for an article
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      - in: path
        name: id
        required: true
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      responses:
        '200':
          content:
            application/json;charset=utf-8: {}
          description: ''
        '404':
          description: '`slug` or `id` not found'
      summary: Delete Comment
      tags:
      - Articles
  /api/articles/{slug}/favorite:
    delete:
      description: Unfavorite an article by slug
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
          description: ''
        '404':
          description: '`slug` not found'
      summary: Unfavorite Article
      tags:
      - Articles
    post:
      description: Favorite an article by slug
      parameters:
      - in: path
        name: slug
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
          description: ''
        '404':
          description: '`slug` not found'
      summary: Favorite Article
      tags:
      - Articles
  /api/metadata:
    get:
      description: Get backend system metadata
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/MetadataResponse'
          description: ''
      summary: Get Metadata
      tags:
      - Profile
  /api/profiles/{username}:
    get:
      description: Get a user profile by username
      parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
          description: ''
        '404':
          description: '`username` not found'
      summary: Get Profile
      tags:
      - Profile
  /api/profiles/{username}/follow:
    delete:
      description: Unfollow a user by username
      parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
          description: ''
        '404':
          description: '`username` not found'
      summary: Unfollow User
      tags:
      - Profile
    post:
      description: Follow a user by username
      parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
          description: ''
        '404':
          description: '`username` not found'
      summary: Follow User
      tags:
      - Profile
  /api/tags:
    get:
      description: Get a list of all tags
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/TagListResponse'
          description: ''
      summary: Get Tags
      tags:
      - Tags
  /api/user:
    get:
      description: Get the currently logged-in user details
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
      summary: Get Current User
      tags:
      - User
    put:
      description: Update the currently logged-in user details
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
        '400':
          description: Invalid `body`
      summary: Update Current User
      tags:
      - User
  /api/users:
    post:
      description: Register a new user
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
      responses:
        '201':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
        '400':
          description: Invalid `body`
      summary: Register
      tags:
      - Authentication
  /api/users/login:
    post:
      description: Login an existing user
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
        '400':
          description: Invalid `body`
      summary: Login
      tags:
      - Authentication
security:
- jwt: []
