name: Nix Dependency Tree

# Triggered manually via the GitHub Actions Tab in the browser
on:
  workflow_dispatch:

jobs:
  nix-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Tree and Print Nix Dependency Tree
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.dry
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
